### PR TITLE
[WAR/GNB] fixes/adjustments

### LINKED ISSUE #195: [GNB] Gnashing Fang Continuation option non-functional
As of 1.0.0.5 the gnashing fang features continuation option has stopped functioning.

Expected behaviour: Gnashing fang replaced with continuation action
Current behaviour: No attempt to replace gnashing fang is made.
 
Checking the code it appears that the continuation section that appears in both the Burst Strike and No Mercy blocks was not included in the Gnashing Fang block.

### PR DESCRIPTION
**Pull request by Akechi-kun**
`WAR`
- [x] Fix typos on `Equilibrium Feature`
- [x] Fix issue with `Primal Combo Feature` not working entirely

`GNB`
- [x] Fix #195 
- [x] Change values as advised on certain config options
(_NOTE:_ was `1 & 2`, now `0 & 1`)
- [x] Change config keys as advised for said options
- [x] Remove obsolete conflicts
- [x] Add `Bozja` options to `Advanced Mode - AoE`
- [x] Add `Include / Exclude Mitigations` options for both `Simple` modes
- [x] Adjust code as advised on mitigations for `Simple` & `Advanced` modes

### CODE REVIEW

File: WrathCombo/Combos/PvE/GNB/GNB.cs [hunk 1]
```diff
@@ -162,24 +162,26 @@ protected override uint Invoke(uint actionID, uint lastComboMove, float comboTim
...
+                            //Rampart
+                            if (ActionReady(All.Rampart) && //Rampart is ready
+                                PlayerHealthPercentageHp() < 80) //Player's health is below 80%
+                                return All.Rampart;
+                        }
+
                         //Superbolide
                         if (ActionReady(Superbolide) && //Superbolide is ready
                             PlayerHealthPercentageHp() < 30) //Player's health is below 30%
                             return Superbolide;
```
Comment (Taurenkey) [inline WrathCombo/Combos/PvE/GNB/GNB.cs:184]: Probably best to put Superbolide to the top of the priority list here (at least until user priority lists are done)

File: WrathCombo/Combos/PvE/GNB/GNB.cs [hunk 2]
```diff
@@ -677,47 +679,49 @@ protected override uint Invoke(uint actionID, uint lastComboMove, float comboTim
...
+
                         //Superbolide
                         if (IsEnabled(CustomComboPreset.GNB_ST_Superbolide) && //Superbolide option is enabled
                             ActionReady(Superbolide) && //Superbolide is ready
                             PlayerHealthPercentageHp() < Config.GNB_ST_Superbolide_Health && //Player's health is below selected threshold
-                            (Config.GNB_ST_Superbolide_SubOption == 1 || //Superbolide is enabled for all targets
-                            (TargetIsBoss() && Config.GNB_ST_Superbolide_SubOption == 2))) //Superbolide is enabled for bosses only
+                            (Config.GNB_ST_Superbolide_SubOption == 0 || //Superbolide is enabled for all targets
+                            (TargetIsBoss() && Config.GNB_ST_Superbolide_SubOption == 1))) //Superbolide is enabled for bosses only
                             return Superbolide;
```
Comment (Taurenkey) [inline WrathCombo/Combos/PvE/GNB/GNB.cs:710]: Again, same as previous with Superbolide priority.

File: WrathCombo/Combos/PvE/GNB/GNB.cs [hunk 3]
```diff
@@ -677,47 +679,49 @@ protected override uint Invoke(uint actionID, uint lastComboMove, float comboTim
...
-                            (Config.GNB_ST_Rampart_SubOption == 1 || //Rampart is enabled for all targets
-                            (TargetIsBoss() && Config.GNB_ST_Rampart_SubOption == 2))) //Rampart is enabled for bosses only
-                            return All.Rampart;
-
                         //Camouflage
                         if (IsEnabled(CustomComboPreset.GNB_ST_Camouflage) && //Camouflage option is enabled
                             ActionReady(Camouflage) && //Camouflage is ready
                             PlayerHealthPercentageHp() < Config.GNB_ST_Camouflage_Health && //Player's health is below selected threshold
-                            (Config.GNB_ST_Camouflage_SubOption == 1 || //Camouflage is enabled for all targets
-                            (TargetIsBoss() && Config.GNB_ST_Camouflage_SubOption == 2))) //Camouflage is enabled for bosses only
```
Comment (Taurenkey) [inline WrathCombo/Combos/PvE/GNB/GNB.cs:712]: This will apply to all the other similar changes, but without resetting the config you'll have users stuck if they selected the old option 2. All you need to do is change the config key and it'll reset it.

File: WrathCombo/Combos/PvE/GNB/GNB_Config.cs [hunk 4]
```diff
@@ -204,11 +229,11 @@ internal static void Draw(CustomComboPreset preset)
 
                     UserConfig.DrawHorizontalRadioButton(GNB_ST_Camouflage_SubOption,
                         "All Enemies",
-                        "Uses Camo regardless of targeted enemy type.", 1);
+                        "Uses Camouflage regardless of targeted enemy type.", 0);
```
Comment (Taurenkey) [inline WrathCombo/Combos/PvE/GNB/GNB_Config.cs:232]: Better to use the localization method I employed in the WAR configs for naming actions rather than hard coding the string value. This applies to all things in the config that can come directly from the game.

**Review by Taurenkey — APPROVED** [review]
