### PR TITLE
[GNB] hey hi hello here's some fixes

### LINKED ISSUE #237: [GNB] Gnashing Fang into Continuation does not appear to function
As of 1.0.0.7, Gnashing Fang -> Continuation does not appear to be functional. I believe this was intended to be fixed by #195.

I am seeing the same issue as the previous. I expect Gnashing Fang to switch to the appropriate Continuation, but this does not seem to happen.

[WrathDebug.txt](https://github.com/user-attachments/files/18241254/WrathDebug.txt)

Edit to add: Every other continuation option (Burst Strike > Hypervelocity, Fated Circle > Fated Brand) works correctly. It's just GF that doesn't.

### LINKED ISSUE #239: [GNB] Inconsistent Continuation interaction with overcap features
Version: 1.0.0.7

# AoE Combo with Overcap

Executing Fated Circle via the Demon Slice button (AoE combo overcap) presents Continuation on the same button if the Fated Circle > Fated Brand feature is active. 

Expected: Demon Slice > Fated Circle > Fated Brand > Demon Slaughter
Observed: Demon Slice > Fated Circle > Fated Brand > Demon Slaughter

# Single Target Combo with Overcap

Executing Burst Strike via the Keen Edge combo (single target overcap) does NOT present Continuation on the same button even if the Burst Strike > Hypervelocity feature is active.

Expected: Keen Edge > Brutal Shell > Burst Strike > Hypervelocity > Solid Barrel
Observed: Keen Edge > Brutal Shell > Burst Strike > Solid Barrel

Note that the respective Continuation options do appear on the associated buttons themselves. In this example, Hypervelocity is presented on the Burst Strike button, but not the Keen Edge button even if overcap is enabled, which is not consistent with AoE button behavior.

[WrathDebug.txt](https://github.com/user-attachments/files/18241285/WrathDebug.txt)

### PR DESCRIPTION
**Pull request by Akechi-kun**
:)

- [x] Fix #237 
- [x] Fix #239 
- [x] Fix issue with odd minute `No Mercy` windows bursting incorrectly

### CODE REVIEW

**Review by Kagekazu — APPROVED** [review]
LGTM

File: WrathCombo/Combos/PvE/GNB/GNB.cs [hunk 1]
```diff
@@ -2026,17 +2030,6 @@ protected override uint Invoke(uint actionID, uint lastComboMove, float comboTim
                     //oGCDs
                     if (CanWeave())
                     {
-                        //Variant SpiritDart
-                        Status? sustainedDamage = FindTargetEffect(Variant.Debuffs.SustainedDamage);
-                        if (IsEnabled(CustomComboPreset.GNB_Variant_SpiritDart) &&
-                            IsEnabled(Variant.VariantSpiritDart) &&
-                            (sustainedDamage is null || sustainedDamage?.RemainingTime <= 3))
-                            return Variant.VariantSpiritDart;
```
Comment (zbee) [inline WrathCombo/Combos/PvE/GNB/GNB.cs:2034]: Confused about the removal of these Variant spell usages, especially when the options are still there in the `CustomComboPreset.cs` file.
Do they not belong in this particular combo, or something?

**Review by zbee — COMMENTED** [review]
Mostly LGTM, but do have a question I raised as a comment about the removal of Variant actions.

**Review by zbee — APPROVED** [review]
