### PR TITLE
[SAM] + [MNK] fix getting stuck 

### LINKED ISSUE #802: Sam single target combat bug
Sam is unable to move past the 3rd combo in the rotation.  it gets stuck at 2 stickers and then starts repeating the combo opener.  This happens after it uses the major stuff like true north and the big "fight start"  combos.  Tried in a dungeon and a strikign dummy and still getting combo locked

### PR DESCRIPTION
**Pull request by Kagekazu**
- Fixes the getting stuck on Fuko/Fuga when u got sens
- Fix Simple mode getting stuck
- Add incombat check for MNK buffs
- Add Riddle of Earth + Earth's rumination raidwide option
- Add Mantra raidwide option
- Fixes #802

### CODE REVIEW

File: WrathCombo/Combos/PvE/MNK/MNK_Helper.cs [hunk 1]
```diff
@@ -101,6 +101,21 @@ internal static bool UseRoW() =>
...
+        RaidWideCasting();
+
+    internal static bool UseRoE() =>
+        ActionReady(RiddleOfEarth) &&
+        !HasStatusEffect(Buffs.RiddleOfEarth) &&
+        !HasStatusEffect(Buffs.EarthsRumination);
+
+    internal static bool UseEarthsRumination() =>
+        HasStatusEffect(Buffs.EarthsRumination) &&
+        !RaidWideCasting() && NumberOfAlliesInRange(EarthsReply) >= GetPartyMembers().Count * .75 &&
```
Comment (edewen) [inline WrathCombo/Combos/PvE/MNK/MNK_Helper.cs:116]: You don't want No raidwide casting here. Earths reply you would want to either help top before the raidwide hits or after it goes off.

**Review by edewen — APPROVED** [review]

File: WrathCombo/Combos/PvE/SAM/SAM.cs [hunk 2]
```diff
@@ -145,8 +145,7 @@ MeditationStacks is 3 &&
                 if (ComboAction is Jinpu && LevelChecked(Gekko))
                     return Gekko;
 
-                if (IsEnabled(Preset.SAM_ST_Kasha) &&
```
Comment (zbee) [inline WrathCombo/Combos/PvE/SAM/SAM.cs:148]: :3

**Review by zbee — APPROVED** [review]
The change above looks fine to be now, logic looks sound in general, not tested in game

**Comment by eclipsaa** [comment]
This is still happening

**Comment by Kagekazu** [comment]
> This is still happening

as i said in ur issue, it is not on live. once u get an update in game it will be solved
